# Generated by Django 4.0.6 on 2022-07-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductEstablishment',
        ),
        migrations.AlterField(
            model_name='productbase',
            name='calories',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='saturated_fat_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='sugar_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
