# Generated by Django 4.0.6 on 2022-07-05 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_product_productestablishment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductBase',
            new_name='Product',
        ),
        migrations.AlterField(
            model_name='productestablishment',
            name='product_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productbase', verbose_name='Product'),
        ),
    ]
