# Generated by Django 4.0.6 on 2022-07-05 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_productbase_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productestablishment',
            name='product_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product', verbose_name='Product'),
        ),
    ]
